# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 19:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(db_index=True, max_length=32)),
                ('field_key', models.CharField(db_index=True, max_length=64)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataview.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionRows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField(db_index=True)),
                ('row', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataview.Collection')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='collectionrows',
            unique_together=set([('collection', 'row_id')]),
        ),
    ]
