# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0002_auto_20161120_1957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollectionRows',
            new_name='Dataset',
        ),
        migrations.RenameModel(
            old_name='CollectionFields',
            new_name='Schemas',
        ),
    ]
